//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RudeBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RudeBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього аккаунтів у цьому чаті:.
        /// </summary>
        internal static string AccountsInTheChat {
            get {
                return ResourceManager.GetString("AccountsInTheChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краще б чимось корисним зайнялись.
        ///Краще б нічого не робили.
        ///Краще б нормальний сайт собі зробили
        ///Краще б Діму полайкали.
        ///Краще б Працювали
        ///Краще б запиталися експертів
        ///Краще б пруф знайшли
        ///Краще б рудебота поробили
        ///Краще б рудекоїнів купили
        ///Я спати
        ///Доброго ранку чат!
        ///Добрий ранок
        ///Краще б тікет спочатку зробили
        ///Буду чекати
        ///вогонь
        ///Відпочивай
        ///я все думаю
        ///то точно:)
        ///також помітив
        ///тим паче у львові
        ///ахаха))))
        ///Фааак)))
        ///Чорно)
        ///Це сильно)
        ///Ахахахах
        ///я довго думав, а потім усмінувся
        ///я довго д [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advices {
            get {
                return ResourceManager.GetString("Advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амністован.
        /// </summary>
        internal static string Amnestied {
            get {
                return ResourceManager.GetString("Amnestied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Думаєш я настільки тупий?.
        /// </summary>
        internal static string AreYouThinkImThatDumb {
            get {
                return ResourceManager.GetString("AreYouThinkImThatDumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to матюків.
        /// </summary>
        internal static string BadWords {
            get {
                return ResourceManager.GetString("BadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cunt
        ///Cyка
        ///kurwa
        ///nahui
        ///pidar
        ///pizd
        ///бля
        ///Бляд
        ///Блядство
        ///Блядь
        ///Блят
        ///Вхуюжить
        ///Выебать
        ///Выеби
        ///Выебон
        ///Гандон
        ///говн
        ///говно
        ///Гомосек
        ///д@ун
        ///Далбоёб
        ///даун
        ///Долбоёб
        ///Ебать
        ///Еби
        ///Ебическая
        ///Еблан
        ///Еблище
        ///Ебло
        ///Ёбнуть
        ///Ёболызнуть
        ///Ебош
        ///Ебунок
        ///Заёб
        ///Заебал
        ///Заебатый
        ///залупа
        ///засран
        ///засранец
        ///засрать
        ///Злаебучий
        ///Иди на хуй
        ///Їбати
        ///Їбатися
        ///їбать
        ///Колдоебина
        ///курва
        ///Манда
        ///Мандовошка
        ///Мокрощелка
        ///Мудак
        ///Наебал
        ///Наебаловка
        ///Наебка
        ///Напиздеть
        ///Опизденеть
        ///Отебукать
        ///Отхуевертить
        ///Отъебись
        ///Охуевший
        ///Охуеть
        ///п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BadWordsDataset {
            get {
                return ResourceManager.GetString("BadWordsDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправився за кораблем.
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанено медіа.
        /// </summary>
        internal static string BannedMedia {
            get {
                return ResourceManager.GetString("BannedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це кнопка для адмінів.
        /// </summary>
        internal static string ButtonOnlyForAdmins {
            get {
                return ResourceManager.GetString("ButtonOnlyForAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Настройки чату:**.
        /// </summary>
        internal static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/awitwicki/rude_bot/main/media/sh.mp4.
        /// </summary>
        internal static string CockmanVideoUrl {
            get {
                return ResourceManager.GetString("CockmanVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда дозволенa тільки для адмінів.
        /// </summary>
        internal static string CommandIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("CommandIsOnlyForAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виконано.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто, альо.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка, щось робиш не так‍.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкета.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Пішов собі далі по своїх справах*.
        /// </summary>
        internal static string GoneAway {
            get {
                return ResourceManager.GetString("GoneAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forms.gle/pY6EjJhNRosUbd9P9.
        /// </summary>
        internal static string GoogleFormForNewbiesURL {
            get {
                return ResourceManager.GetString("GoogleFormForNewbiesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-davinci-003.
        /// </summary>
        internal static string GPTModel {
            get {
                return ResourceManager.GetString("GPTModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой у нас тут &quot;хакер&quot; в чаті 😐, такого тікету не існує....
        /// </summary>
        internal static string HackerInTheChat {
            get {
                return ResourceManager.GetString("HackerInTheChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо {0} у нашому чаті!
        ///Ми не чат, а дружня, толерантна IT спільнота, яка поважає думку кожного, приєднавшись,
        ///ти згоджуєшся стати чемною частиною спільноти (та полюбити епл).
        ///
        ///I якшо не важко, пліз тут анкета на 8 питань.
        /// </summary>
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я обіцяю!.
        /// </summary>
        internal static string IAmPromise {
            get {
                return ResourceManager.GetString("IAmPromise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт, я Рудекіт!
        ///
        ///Я можу дещо зробити, якшо ти скажеш чарівне слово:
        ///`Карма` - покажу твою карму,
        ///`Топ` - покажу топ учасників чату,
        ///`Тесла` - порахую дні без згадування тесли,
        ///`/cat` або `Кіт` - покажу котика,
        ///`Шарій` - покажу півника,
        ///`Зрада` - розпочну процедуру бану,
        ///`/warn /unwarn` - (admins only) винесу попередження за погану поведінку,
        ///`/scan` - (admins only) просканую когось,
        ///`/give {{25}}` - поділитися 25 рудекоїнами,
        ///`/tickets` - випишу всі таски чату,
        ///`/addticket {{купити молочка к [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/awitwicki/rude_bot/main/media/itsuachat.mp4.
        /// </summary>
        internal static string ItsUaChatVideoUrl {
            get {
                return ResourceManager.GetString("ItsUaChatVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to карма.
        /// </summary>
        internal static string Karma {
            get {
                return ResourceManager.GetString("Karma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви зменшили карму {0} до значення {1}!.
        /// </summary>
        internal static string KarmaDecrease {
            get {
                return ResourceManager.GetString("KarmaDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви збільшили карму {0} до значення {1}! 🥳.
        /// </summary>
        internal static string KarmaIncrease {
            get {
                return ResourceManager.GetString("KarmaIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викинуто з чату.
        /// </summary>
        internal static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про це вже писали.
        /// </summary>
        internal static string Klichko {
            get {
                return ResourceManager.GetString("Klichko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи:.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to повідомлень.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мут на день.
        /// </summary>
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треба вказати текст тікету після команди.
        /// </summary>
        internal static string NeedToDefineTicket {
            get {
                return ResourceManager.GetString("NeedToDefineTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дуже раді вас бачити! Будь ласка, ознайомтеся з Конституцією чату в закріплених повідомленнях..
        /// </summary>
        internal static string NewbieClicked {
            get {
                return ResourceManager.GetString("NewbieClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не виконано.
        /// </summary>
        internal static string NotDone {
            get {
                return ResourceManager.GetString("NotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще раз і бан :).
        /// </summary>
        internal static string OnceAgaInAndGetBaned {
            get {
                return ResourceManager.GetString("OnceAgaInAndGetBaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дозволено тільки для адмінів.
        /// </summary>
        internal static string OnlyAdminsAreAllowed {
            get {
                return ResourceManager.GetString("OnlyAdminsAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! …I Didn&apos;t again.
        /// </summary>
        internal static string OopsIDidntAgain {
            get {
                return ResourceManager.GetString("OopsIDidntAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ану кажи &quot;паляниця&quot; 😡.
        /// </summary>
        internal static string Palanytsia {
            get {
                return ResourceManager.GetString("Palanytsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://awitwicki.github.io/rude_bot/.
        /// </summary>
        internal static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/awitwicki/rude_bot/main/media/punish.mp4.
        /// </summary>
        internal static string PunishVideoUrl {
            get {
                return ResourceManager.GetString("PunishVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правильно|Не правильно :(|Рофлиш?)|Уважно подивись :)|Добре, вгадав|Даю ще одну спробу|За таке можна і забанити|Як не вгадаєш з трьох раз то летиш до бану :).
        /// </summary>
        internal static string RandomCatGenders {
            get {
                return ResourceManager.GetString("RandomCatGenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Російська пропаганда (.ru .рф .сру і інші) не може вважатися пруфом!*
        ///
        ///Вас буде додано до реєстру..
        /// </summary>
        internal static string ruPropaganda {
            get {
                return ResourceManager.GetString("ruPropaganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хейт російської мови в повідомленнях:.
        /// </summary>
        internal static string russianLangHate {
            get {
                return ResourceManager.GetString("russianLangHate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включити/виключити хейт російської (тільки для адмінів): /haterusianlang.
        /// </summary>
        internal static string russianLangHateCommandDescription {
            get {
                return ResourceManager.GetString("russianLangHateCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепер я НЕ хейчу за русняву мову в чаті.
        /// </summary>
        internal static string russianLangHateOff {
            get {
                return ResourceManager.GetString("russianLangHateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепер я хейчу за русняву мову в чаті.
        /// </summary>
        internal static string russianLangHateOn {
            get {
                return ResourceManager.GetString("russianLangHateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/awitwicki/rude_bot/main/media/samsung.jpg.
        /// </summary>
        internal static string SamsungUrl {
            get {
                return ResourceManager.GetString("SamsungUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /scan дозволений тільки для адмінів.
        /// </summary>
        internal static string ScanIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("ScanIsOnlyForAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /scan має бути відповіддю, на чиєсь повідомлення (боти не рахуються).
        /// </summary>
        internal static string ScanNeedsToBeReplyToMessage {
            get {
                return ResourceManager.GetString("ScanNeedsToBeReplyToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час від часу писати повідомлення.
        /// </summary>
        internal static string SendRandomMessages {
            get {
                return ResourceManager.GetString("SendRandomMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час від часу писати повідомлення в чат (тільки для адмінів) /sendrandommessages.
        /// </summary>
        internal static string SendRandomMessagesDescription {
            get {
                return ResourceManager.GetString("SendRandomMessagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепер я не буду писати час від часу в чаті.
        /// </summary>
        internal static string SendRandomMessagesOff {
            get {
                return ResourceManager.GetString("SendRandomMessagesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепер я буду писати час від часу в чаті.
        /// </summary>
        internal static string SendRandomMessagesOn {
            get {
                return ResourceManager.GetString("SendRandomMessagesOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Днів без згадування тесли: `0`
        ///🚗🚗🚗
        ///
        ///...btw ${0}.
        /// </summary>
        internal static string TeslaAgain {
            get {
                return ResourceManager.GetString("TeslaAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тікет &quot;{0}&quot; додано до чату..
        /// </summary>
        internal static string TicketAdded {
            get {
                return ResourceManager.GetString("TicketAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тікет номер &quot;{0}&quot; видалено..
        /// </summary>
        internal static string TicketDeleted {
            get {
                return ResourceManager.GetString("TicketDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 актив чату:*.
        /// </summary>
        internal static string TopChatActive {
            get {
                return ResourceManager.GetString("TopChatActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 емоціонали чату:*.
        /// </summary>
        internal static string TopChatEmotionals {
            get {
                return ResourceManager.GetString("TopChatEmotionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 карми чату:*.
        /// </summary>
        internal static string TopChatKarma {
            get {
                return ResourceManager.GetString("TopChatKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ -3 карми чату:*.
        /// </summary>
        internal static string TopChatNegativeKarma {
            get {
                return ResourceManager.GetString("TopChatNegativeKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 варни чату:*.
        /// </summary>
        internal static string TopChatWarns {
            get {
                return ResourceManager.GetString("TopChatWarns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatGPT:.
        /// </summary>
        internal static string UseChatGPT {
            get {
                return ResourceManager.GetString("UseChatGPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включити/виключити режим ChatGPT (тільки для адмінів): /usechatgpt.
        /// </summary>
        internal static string UseChatGPTCommandDescription {
            get {
                return ResourceManager.GetString("UseChatGPTCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепер я НЕ буду відповідати як ChatGPT.
        /// </summary>
        internal static string UseChatGPTOff {
            get {
                return ResourceManager.GetString("UseChatGPTOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тепер я буду відповідати як ChatGPT.
        /// </summary>
        internal static string UseChatGPTOn {
            get {
                return ResourceManager.GetString("UseChatGPTOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На балансі ще {0} попередженнь.
        /// </summary>
        internal static string WarnBalance {
            get {
                return ResourceManager.GetString("WarnBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to попередження анульовано!.
        /// </summary>
        internal static string WarnCancelled {
            get {
                return ResourceManager.GetString("WarnCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to варн.
        /// </summary>
        internal static string Warned {
            get {
                return ResourceManager.GetString("Warned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /warn або /unwarn дозволений тільки для адмінів.
        /// </summary>
        internal static string WarnOrUnwarnIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("WarnOrUnwarnIsOnlyForAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /warn або /unwarn має бути відповіддю, на чиєсь повідомлення.
        /// </summary>
        internal static string WarnOrUnwarnNeedsToBeReplyToMessage {
            get {
                return ResourceManager.GetString("WarnOrUnwarnNeedsToBeReplyToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /warn або /unwarn не діє на адмінів.
        /// </summary>
        internal static string WarnOrUnwarnNotWorksOnAdmins {
            get {
                return ResourceManager.GetString("WarnOrUnwarnNotWorksOnAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to варнів.
        /// </summary>
        internal static string Warns {
            get {
                return ResourceManager.GetString("Warns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/awitwicki/rude_bot/main/media/welcome.mp4.
        /// </summary>
        internal static string WelcomeToTheClubBuddyVideoUrl {
            get {
                return ResourceManager.GetString("WelcomeToTheClubBuddyVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Де, блять, номер тікету після команди?.
        /// </summary>
        internal static string WhereIsTicketNumber {
            get {
                return ResourceManager.GetString("WhereIsTicketNumber", resourceCulture);
            }
        }
    }
}
