//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RudeBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RudeBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всього аккаунтів у цьому чаті:.
        /// </summary>
        internal static string AccountsInTheChat {
            get {
                return ResourceManager.GetString("AccountsInTheChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краще б чимось корисним зайнялись.
        ///Краще б нічого не робили.
        ///Краще б нормальний сайт собі зробили
        ///Краще б Діму полайкали.
        ///Краще б Працювали
        ///Краще б запиталися експертів
        ///Краще б пруф знайшли
        ///Краще б рудебота поробили
        ///Краще б рудекоїнів купили
        ///Я спати
        ///Доброго ранку чат!
        ///Добрий ранок
        ///Краще б тікет спочатку зробили
        ///Буду чекати
        ///вогонь
        ///Відпочивай
        ///я все думаю
        ///то точно:)
        ///також помітив
        ///тим паче у львові
        ///ахаха))))
        ///Фааак)))
        ///Чорно)
        ///Це сильно)
        ///Ахахахах
        ///я довго думав, а потім усмінувся
        ///я довго д [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advices {
            get {
                return ResourceManager.GetString("Advices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Думаєш я настільки тупий?.
        /// </summary>
        internal static string AreYouThinkImThatDumb {
            get {
                return ResourceManager.GetString("AreYouThinkImThatDumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to матюків.
        /// </summary>
        internal static string BadWords {
            get {
                return ResourceManager.GetString("BadWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cunt
        ///Cyка
        ///kurwa
        ///nahui
        ///pidar
        ///pizd
        ///бля
        ///Бляд
        ///Блядство
        ///Блядь
        ///Блят
        ///Вхуюжить
        ///Выебать
        ///Выеби
        ///Выебон
        ///Гандон
        ///говн
        ///говно
        ///Гомосек
        ///д@ун
        ///Далбоёб
        ///даун
        ///Долбоёб
        ///Ебать
        ///Еби
        ///Ебическая
        ///Еблан
        ///Еблище
        ///Ебло
        ///Ёбнуть
        ///Ёболызнуть
        ///Ебош
        ///Ебунок
        ///Заёб
        ///Заебал
        ///Заебатый
        ///залупа
        ///засран
        ///засранец
        ///засрать
        ///Злаебучий
        ///Иди на хуй
        ///Їбати
        ///Їбатися
        ///їбать
        ///Колдоебина
        ///курва
        ///Манда
        ///Мандовошка
        ///Мокрощелка
        ///Мудак
        ///Наебал
        ///Наебаловка
        ///Наебка
        ///Напиздеть
        ///Опизденеть
        ///Отебукать
        ///Отхуевертить
        ///Отъебись
        ///Охуевший
        ///Охуеть
        ///п [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BadWordsDataset {
            get {
                return ResourceManager.GetString("BadWordsDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто, альо.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Пішов собі далі по своїх справах*.
        /// </summary>
        internal static string GoneAway {
            get {
                return ResourceManager.GetString("GoneAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-davinci-003.
        /// </summary>
        internal static string GPTModel {
            get {
                return ResourceManager.GetString("GPTModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой у нас тут &quot;хакер&quot; в чаті 😐, такого тікету не існує....
        /// </summary>
        internal static string HackerInTheChat {
            get {
                return ResourceManager.GetString("HackerInTheChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт, я Рудекіт!
        ///
        ///Я можу дещо зробити, якшо ти скажеш чарівне слово:
        ///`Карма` - покажу твою карму,
        ///`Топ` - покажу топ учасників чату,
        ///`Тесла` - порахую дні без згадування тесли,
        ///`/cat` або `Кіт` - покажу котика,
        ///`Шарій` - покажу півника,
        ///`Зрада` - розпочну процедуру бану,
        ///`/warn /unwarn` - (admins only) винесу попередження за погану поведінку,
        ///`/scan` - (admins only) просканую когось,
        ///`/give {{25}}` - поділитися 25 рудекоїнами,
        ///`/tickets` - випишу всі таски чату,
        ///`/addticket {{купити молочка к [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to карма.
        /// </summary>
        internal static string Karma {
            get {
                return ResourceManager.GetString("Karma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви зменшили карму {0} до значення {1}!.
        /// </summary>
        internal static string KarmaDecrease {
            get {
                return ResourceManager.GetString("KarmaDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви збільшили карму {0} до значення {1}! 🥳.
        /// </summary>
        internal static string KarmaIncrease {
            get {
                return ResourceManager.GetString("KarmaIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про це вже писали.
        /// </summary>
        internal static string Klichko {
            get {
                return ResourceManager.GetString("Klichko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to повідомлень.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треба вказати текст тікету після команди.
        /// </summary>
        internal static string NeedToDefineTicket {
            get {
                return ResourceManager.GetString("NeedToDefineTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дозволено тільки для адмінів.
        /// </summary>
        internal static string OnlyAdminsAreAllowed {
            get {
                return ResourceManager.GetString("OnlyAdminsAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! …I Didn&apos;t again.
        /// </summary>
        internal static string OopsIDidntAgain {
            get {
                return ResourceManager.GetString("OopsIDidntAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ану кажи &quot;паляниця&quot; 😡.
        /// </summary>
        internal static string Palanytsia {
            get {
                return ResourceManager.GetString("Palanytsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правильно|Не правильно :(|Рофлиш?)|Уважно подивись :)|Добре, вгадав|Даю ще одну спробу|За таке можна і забанити|Як не вгадаєш з трьох раз то летиш до бану :).
        /// </summary>
        internal static string RandomCatGenders {
            get {
                return ResourceManager.GetString("RandomCatGenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Російська пропаганда (.ru .рф .сру і інші) не може вважатися пруфом!*
        ///
        ///Вас буде додано до реєстру..
        /// </summary>
        internal static string ruPropaganda {
            get {
                return ResourceManager.GetString("ruPropaganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Днів без згадування тесли: `0`
        ///🚗🚗🚗
        ///
        ///...btw ${0}.
        /// </summary>
        internal static string TeslaAgain {
            get {
                return ResourceManager.GetString("TeslaAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тікет &quot;{0}&quot; додано до чату..
        /// </summary>
        internal static string TicketAdded {
            get {
                return ResourceManager.GetString("TicketAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тікет номер &quot;{0}&quot; видалено..
        /// </summary>
        internal static string TicketDeleted {
            get {
                return ResourceManager.GetString("TicketDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 актив чату:*.
        /// </summary>
        internal static string TopChatActive {
            get {
                return ResourceManager.GetString("TopChatActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 емоціонали чату:*.
        /// </summary>
        internal static string TopChatEmotionals {
            get {
                return ResourceManager.GetString("TopChatEmotionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 карми чату:*.
        /// </summary>
        internal static string TopChatKarma {
            get {
                return ResourceManager.GetString("TopChatKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ -3 карми чату:*.
        /// </summary>
        internal static string TopChatNegativeKarma {
            get {
                return ResourceManager.GetString("TopChatNegativeKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Топ 5 варни чату:*.
        /// </summary>
        internal static string TopChatWarns {
            get {
                return ResourceManager.GetString("TopChatWarns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to варнів.
        /// </summary>
        internal static string Warns {
            get {
                return ResourceManager.GetString("Warns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Де, блять, номер тікету після команди?.
        /// </summary>
        internal static string WhereIsTicketNumber {
            get {
                return ResourceManager.GetString("WhereIsTicketNumber", resourceCulture);
            }
        }
    }
}
