//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RudeBot {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RudeBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        internal static string ruPropaganda {
            get {
                return ResourceManager.GetString("ruPropaganda", resourceCulture);
            }
        }
        
        internal static string Palanytsia {
            get {
                return ResourceManager.GetString("Palanytsia", resourceCulture);
            }
        }
        
        internal static string TeslaAgain {
            get {
                return ResourceManager.GetString("TeslaAgain", resourceCulture);
            }
        }
        
        internal static string KarmaIncrease {
            get {
                return ResourceManager.GetString("KarmaIncrease", resourceCulture);
            }
        }
        
        internal static string KarmaDecrease {
            get {
                return ResourceManager.GetString("KarmaDecrease", resourceCulture);
            }
        }
        
        internal static string OnlyAdminsAreAllowed {
            get {
                return ResourceManager.GetString("OnlyAdminsAreAllowed", resourceCulture);
            }
        }
        
        internal static string OopsIDidntAgain {
            get {
                return ResourceManager.GetString("OopsIDidntAgain", resourceCulture);
            }
        }
        
        internal static string GPTModel {
            get {
                return ResourceManager.GetString("GPTModel", resourceCulture);
            }
        }
        
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        internal static string RandomCatGenders {
            get {
                return ResourceManager.GetString("RandomCatGenders", resourceCulture);
            }
        }
        
        internal static string AreYouThinkImThatDumb {
            get {
                return ResourceManager.GetString("AreYouThinkImThatDumb", resourceCulture);
            }
        }
        
        internal static string TicketDeleted {
            get {
                return ResourceManager.GetString("TicketDeleted", resourceCulture);
            }
        }
        
        internal static string HackerInTheChat {
            get {
                return ResourceManager.GetString("HackerInTheChat", resourceCulture);
            }
        }
        
        internal static string WhereIsTicketNumber {
            get {
                return ResourceManager.GetString("WhereIsTicketNumber", resourceCulture);
            }
        }
        
        internal static string GoneAway {
            get {
                return ResourceManager.GetString("GoneAway", resourceCulture);
            }
        }
        
        internal static string NeedToDefineTicket {
            get {
                return ResourceManager.GetString("NeedToDefineTicket", resourceCulture);
            }
        }
        
        internal static string TicketAdded {
            get {
                return ResourceManager.GetString("TicketAdded", resourceCulture);
            }
        }
        
        internal static string Karma {
            get {
                return ResourceManager.GetString("Karma", resourceCulture);
            }
        }
        
        internal static string TopChatActive {
            get {
                return ResourceManager.GetString("TopChatActive", resourceCulture);
            }
        }
        
        internal static string AccountsInTheChat {
            get {
                return ResourceManager.GetString("AccountsInTheChat", resourceCulture);
            }
        }
        
        internal static string TopChatKarma {
            get {
                return ResourceManager.GetString("TopChatKarma", resourceCulture);
            }
        }
        
        internal static string TopChatNegativeKarma {
            get {
                return ResourceManager.GetString("TopChatNegativeKarma", resourceCulture);
            }
        }
        
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        internal static string BadWords {
            get {
                return ResourceManager.GetString("BadWords", resourceCulture);
            }
        }
        
        internal static string TopChatWarns {
            get {
                return ResourceManager.GetString("TopChatWarns", resourceCulture);
            }
        }
        
        internal static string Warns {
            get {
                return ResourceManager.GetString("Warns", resourceCulture);
            }
        }
        
        internal static string TopChatEmotionals {
            get {
                return ResourceManager.GetString("TopChatEmotionals", resourceCulture);
            }
        }
        
        internal static string Advices {
            get {
                return ResourceManager.GetString("Advices", resourceCulture);
            }
        }
        
        internal static string BadWordsDataset {
            get {
                return ResourceManager.GetString("BadWordsDataset", resourceCulture);
            }
        }
        
        internal static string Klichko {
            get {
                return ResourceManager.GetString("Klichko", resourceCulture);
            }
        }
        
        internal static string GoogleFormForNewbiesURL {
            get {
                return ResourceManager.GetString("GoogleFormForNewbiesURL", resourceCulture);
            }
        }
        
        internal static string WelcomeToTheClubBuddyVideoUrl {
            get {
                return ResourceManager.GetString("WelcomeToTheClubBuddyVideoUrl", resourceCulture);
            }
        }
        
        internal static string CockmanVideoUrl {
            get {
                return ResourceManager.GetString("CockmanVideoUrl", resourceCulture);
            }
        }
        
        internal static string SamsungUrl {
            get {
                return ResourceManager.GetString("SamsungUrl", resourceCulture);
            }
        }
        
        internal static string PunishVideoUrl {
            get {
                return ResourceManager.GetString("PunishVideoUrl", resourceCulture);
            }
        }
        
        internal static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        internal static string NewbieClicked {
            get {
                return ResourceManager.GetString("NewbieClicked", resourceCulture);
            }
        }
        
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        internal static string IAmPromise {
            get {
                return ResourceManager.GetString("IAmPromise", resourceCulture);
            }
        }
        
        internal static string OnceAgaInAndGetBaned {
            get {
                return ResourceManager.GetString("OnceAgaInAndGetBaned", resourceCulture);
            }
        }
        
        internal static string WarnOrUnwarnIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("WarnOrUnwarnIsOnlyForAdmins", resourceCulture);
            }
        }
        
        internal static string WarnOrUnwarnNeedsToBeReplyToMessage {
            get {
                return ResourceManager.GetString("WarnOrUnwarnNeedsToBeReplyToMessage", resourceCulture);
            }
        }
        
        internal static string ButtonOnlyForAdmins {
            get {
                return ResourceManager.GetString("ButtonOnlyForAdmins", resourceCulture);
            }
        }
        
        internal static string CommandIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("CommandIsOnlyForAdmins", resourceCulture);
            }
        }
        
        internal static string WarnOrUnwarnNotWorksOnAdmins {
            get {
                return ResourceManager.GetString("WarnOrUnwarnNotWorksOnAdmins", resourceCulture);
            }
        }
        
        internal static string NotDone {
            get {
                return ResourceManager.GetString("NotDone", resourceCulture);
            }
        }
        
        internal static string BannedMedia {
            get {
                return ResourceManager.GetString("BannedMedia", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string ScanIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("ScanIsOnlyForAdmins", resourceCulture);
            }
        }
        
        internal static string ScanNeedsToBeReplyToMessage {
            get {
                return ResourceManager.GetString("ScanNeedsToBeReplyToMessage", resourceCulture);
            }
        }
        
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        internal static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        internal static string Warned {
            get {
                return ResourceManager.GetString("Warned", resourceCulture);
            }
        }
        
        internal static string Amnestied {
            get {
                return ResourceManager.GetString("Amnestied", resourceCulture);
            }
        }
        
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        internal static string WarnBalance {
            get {
                return ResourceManager.GetString("WarnBalance", resourceCulture);
            }
        }
        
        internal static string WarnCancelled {
            get {
                return ResourceManager.GetString("WarnCancelled", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        internal static string russianLangHate {
            get {
                return ResourceManager.GetString("russianLangHate", resourceCulture);
            }
        }
        
        internal static string russianLangHateCommandDescription {
            get {
                return ResourceManager.GetString("russianLangHateCommandDescription", resourceCulture);
            }
        }
        
        internal static string russianLangHateOn {
            get {
                return ResourceManager.GetString("russianLangHateOn", resourceCulture);
            }
        }
        
        internal static string russianLangHateOff {
            get {
                return ResourceManager.GetString("russianLangHateOff", resourceCulture);
            }
        }
        
        internal static string UseChatGPT {
            get {
                return ResourceManager.GetString("UseChatGPT", resourceCulture);
            }
        }
        
        internal static string UseChatGPTCommandDescription {
            get {
                return ResourceManager.GetString("UseChatGPTCommandDescription", resourceCulture);
            }
        }
        
        internal static string UseChatGPTOn {
            get {
                return ResourceManager.GetString("UseChatGPTOn", resourceCulture);
            }
        }
        
        internal static string UseChatGPTOff {
            get {
                return ResourceManager.GetString("UseChatGPTOff", resourceCulture);
            }
        }
        
        internal static string SendRandomMessages {
            get {
                return ResourceManager.GetString("SendRandomMessages", resourceCulture);
            }
        }
        
        internal static string SendRandomMessagesOn {
            get {
                return ResourceManager.GetString("SendRandomMessagesOn", resourceCulture);
            }
        }
        
        internal static string SendRandomMessagesOff {
            get {
                return ResourceManager.GetString("SendRandomMessagesOff", resourceCulture);
            }
        }
        
        internal static string SendRandomMessagesDescription {
            get {
                return ResourceManager.GetString("SendRandomMessagesDescription", resourceCulture);
            }
        }
        
        internal static string ItsUaChatVideoUrl {
            get {
                return ResourceManager.GetString("ItsUaChatVideoUrl", resourceCulture);
            }
        }
    }
}
