//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RudeBot.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RudeBot.Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        public static string ruPropaganda {
            get {
                return ResourceManager.GetString("ruPropaganda", resourceCulture);
            }
        }
        
        public static string Palanytsia {
            get {
                return ResourceManager.GetString("Palanytsia", resourceCulture);
            }
        }
        
        public static string TeslaAgain {
            get {
                return ResourceManager.GetString("TeslaAgain", resourceCulture);
            }
        }
        
        public static string KarmaIncrease {
            get {
                return ResourceManager.GetString("KarmaIncrease", resourceCulture);
            }
        }
        
        public static string KarmaDecrease {
            get {
                return ResourceManager.GetString("KarmaDecrease", resourceCulture);
            }
        }
        
        public static string OnlyAdminsAreAllowed {
            get {
                return ResourceManager.GetString("OnlyAdminsAreAllowed", resourceCulture);
            }
        }
        
        public static string OopsIDidntAgain {
            get {
                return ResourceManager.GetString("OopsIDidntAgain", resourceCulture);
            }
        }
        
        public static string GPTModel {
            get {
                return ResourceManager.GetString("GPTModel", resourceCulture);
            }
        }
        
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        public static string RandomCatGenders {
            get {
                return ResourceManager.GetString("RandomCatGenders", resourceCulture);
            }
        }
        
        public static string AreYouThinkImThatDumb {
            get {
                return ResourceManager.GetString("AreYouThinkImThatDumb", resourceCulture);
            }
        }
        
        public static string TicketDeleted {
            get {
                return ResourceManager.GetString("TicketDeleted", resourceCulture);
            }
        }
        
        public static string HackerInTheChat {
            get {
                return ResourceManager.GetString("HackerInTheChat", resourceCulture);
            }
        }
        
        public static string WhereIsTicketNumber {
            get {
                return ResourceManager.GetString("WhereIsTicketNumber", resourceCulture);
            }
        }
        
        public static string GoneAway {
            get {
                return ResourceManager.GetString("GoneAway", resourceCulture);
            }
        }
        
        public static string NeedToDefineTicket {
            get {
                return ResourceManager.GetString("NeedToDefineTicket", resourceCulture);
            }
        }
        
        public static string TicketAdded {
            get {
                return ResourceManager.GetString("TicketAdded", resourceCulture);
            }
        }
        
        public static string Karma {
            get {
                return ResourceManager.GetString("Karma", resourceCulture);
            }
        }
        
        public static string TopChatActive {
            get {
                return ResourceManager.GetString("TopChatActive", resourceCulture);
            }
        }
        
        public static string AccountsInTheChat {
            get {
                return ResourceManager.GetString("AccountsInTheChat", resourceCulture);
            }
        }
        
        public static string TopChatKarma {
            get {
                return ResourceManager.GetString("TopChatKarma", resourceCulture);
            }
        }
        
        public static string TopChatNegativeKarma {
            get {
                return ResourceManager.GetString("TopChatNegativeKarma", resourceCulture);
            }
        }
        
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        public static string BadWords {
            get {
                return ResourceManager.GetString("BadWords", resourceCulture);
            }
        }
        
        public static string TopChatWarns {
            get {
                return ResourceManager.GetString("TopChatWarns", resourceCulture);
            }
        }
        
        public static string Warns {
            get {
                return ResourceManager.GetString("Warns", resourceCulture);
            }
        }
        
        public static string TopChatEmotionals {
            get {
                return ResourceManager.GetString("TopChatEmotionals", resourceCulture);
            }
        }
        
        public static string Klichko {
            get {
                return ResourceManager.GetString("Klichko", resourceCulture);
            }
        }
        
        public static string GoogleFormForNewbiesURL {
            get {
                return ResourceManager.GetString("GoogleFormForNewbiesURL", resourceCulture);
            }
        }
        
        public static string WelcomeToTheClubBuddyVideoUrl {
            get {
                return ResourceManager.GetString("WelcomeToTheClubBuddyVideoUrl", resourceCulture);
            }
        }
        
        public static string CockmanVideoUrl {
            get {
                return ResourceManager.GetString("CockmanVideoUrl", resourceCulture);
            }
        }
        
        public static string SamsungUrl {
            get {
                return ResourceManager.GetString("SamsungUrl", resourceCulture);
            }
        }
        
        public static string PunishVideoUrl {
            get {
                return ResourceManager.GetString("PunishVideoUrl", resourceCulture);
            }
        }
        
        public static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        public static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        public static string NewbieClicked {
            get {
                return ResourceManager.GetString("NewbieClicked", resourceCulture);
            }
        }
        
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        public static string IAmPromise {
            get {
                return ResourceManager.GetString("IAmPromise", resourceCulture);
            }
        }
        
        public static string OnceAgaInAndGetBaned {
            get {
                return ResourceManager.GetString("OnceAgaInAndGetBaned", resourceCulture);
            }
        }
        
        public static string WarnOrUnwarnIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("WarnOrUnwarnIsOnlyForAdmins", resourceCulture);
            }
        }
        
        public static string ShouldBeReplyToMessage {
            get {
                return ResourceManager.GetString("ShouldBeReplyToMessage", resourceCulture);
            }
        }
        
        public static string ButtonOnlyForAdmins {
            get {
                return ResourceManager.GetString("ButtonOnlyForAdmins", resourceCulture);
            }
        }
        
        public static string CommandIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("CommandIsOnlyForAdmins", resourceCulture);
            }
        }
        
        public static string WarnOrUnwarnNotWorksOnAdmins {
            get {
                return ResourceManager.GetString("WarnOrUnwarnNotWorksOnAdmins", resourceCulture);
            }
        }
        
        public static string NotDone {
            get {
                return ResourceManager.GetString("NotDone", resourceCulture);
            }
        }
        
        public static string BannedMedia {
            get {
                return ResourceManager.GetString("BannedMedia", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string ScanIsOnlyForAdmins {
            get {
                return ResourceManager.GetString("ScanIsOnlyForAdmins", resourceCulture);
            }
        }
        
        public static string ScanNeedsToBeReplyToMessage {
            get {
                return ResourceManager.GetString("ScanNeedsToBeReplyToMessage", resourceCulture);
            }
        }
        
        public static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        public static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        public static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        public static string Warned {
            get {
                return ResourceManager.GetString("Warned", resourceCulture);
            }
        }
        
        public static string Amnestied {
            get {
                return ResourceManager.GetString("Amnestied", resourceCulture);
            }
        }
        
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        public static string WarnBalance {
            get {
                return ResourceManager.GetString("WarnBalance", resourceCulture);
            }
        }
        
        public static string WarnCancelled {
            get {
                return ResourceManager.GetString("WarnCancelled", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ChatSettings {
            get {
                return ResourceManager.GetString("ChatSettings", resourceCulture);
            }
        }
        
        public static string russianLangHate {
            get {
                return ResourceManager.GetString("russianLangHate", resourceCulture);
            }
        }
        
        public static string russianLangHateCommandDescription {
            get {
                return ResourceManager.GetString("russianLangHateCommandDescription", resourceCulture);
            }
        }
        
        public static string russianLangHateOn {
            get {
                return ResourceManager.GetString("russianLangHateOn", resourceCulture);
            }
        }
        
        public static string russianLangHateOff {
            get {
                return ResourceManager.GetString("russianLangHateOff", resourceCulture);
            }
        }
        
        public static string UseChatGPT {
            get {
                return ResourceManager.GetString("UseChatGPT", resourceCulture);
            }
        }
        
        public static string UseChatGPTCommandDescription {
            get {
                return ResourceManager.GetString("UseChatGPTCommandDescription", resourceCulture);
            }
        }
        
        public static string UseChatGPTOn {
            get {
                return ResourceManager.GetString("UseChatGPTOn", resourceCulture);
            }
        }
        
        public static string UseChatGPTOff {
            get {
                return ResourceManager.GetString("UseChatGPTOff", resourceCulture);
            }
        }
        
        public static string SendRandomMessages {
            get {
                return ResourceManager.GetString("SendRandomMessages", resourceCulture);
            }
        }
        
        public static string SendRandomMessagesOn {
            get {
                return ResourceManager.GetString("SendRandomMessagesOn", resourceCulture);
            }
        }
        
        public static string SendRandomMessagesOff {
            get {
                return ResourceManager.GetString("SendRandomMessagesOff", resourceCulture);
            }
        }
        
        public static string SendRandomMessagesDescription {
            get {
                return ResourceManager.GetString("SendRandomMessagesDescription", resourceCulture);
            }
        }
        
        public static string ItsUaChatVideoUrl {
            get {
                return ResourceManager.GetString("ItsUaChatVideoUrl", resourceCulture);
            }
        }
        
        public static string NotEnoughRudeCoins {
            get {
                return ResourceManager.GetString("NotEnoughRudeCoins", resourceCulture);
            }
        }
        
        public static string RudeCoinsTransactionSuccess {
            get {
                return ResourceManager.GetString("RudeCoinsTransactionSuccess", resourceCulture);
            }
        }
        
        public static string CantSendToYourself {
            get {
                return ResourceManager.GetString("CantSendToYourself", resourceCulture);
            }
        }
        
        public static string CantSendToBots {
            get {
                return ResourceManager.GetString("CantSendToBots", resourceCulture);
            }
        }
        
        public static string CanGiveOnlyNumbersArg {
            get {
                return ResourceManager.GetString("CanGiveOnlyNumbersArg", resourceCulture);
            }
        }
        
        public static string Advices {
            get {
                return ResourceManager.GetString("Advices", resourceCulture);
            }
        }
        
        public static string BadWordsDataset {
            get {
                return ResourceManager.GetString("BadWordsDataset", resourceCulture);
            }
        }
    }
}
